### ISSUE TITLE
記事管理をnotionからgithub（別リポジトリ）に変更する

### ISSUE THREAD

**Issue by shabaraba** [shabaraba/shabaraba#44]

**Comment by shabaraba** [comment]
## article用リポジトリ構成案

- 一覧画面用.toml
- articlesディレクトリ
  - 各article.md

## 一覧画面用.toml

```toml
[articles]
[[articles.meta]]
title = "xxx"
uri = "/xxx/yyy"
cover = "xxx/yyy.png"
published = true
tags = ["aaa","bbb","ccc"]
```

## article.md

- タイトル.mdにする
- 特にメタデータは書かない、一覧画面から遷移時に引数で貰えば良さそう

## その他
mylinksはnotion web clipperでサクッと更新できるのが良いので、継続
→ ただしいつでも切り離せるようにはしておきたい
